---
- name: Install Git, Java 17, Maven manually, clone repo, and build via shell script
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no

  vars:
    maven_version: "3.9.10"
    maven_dir: "apache-maven-3.9.10"
    maven_url: "https://downloads.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz"
    maven_path: "/root/maven"
    repo_url: "https://github.com/ManojVattikuti982/sak_group_spring_app.git"
    project_name: "sak_group_spring_app"
    project_path: "/root/sak_group_spring_app"

  tasks:

    - name: Install Java 17 and Git
      shell: yum install java-17* git -y

    - name: Download Maven
      command: wget "{{ maven_url }}" -O /tmp/apache-maven.tar.gz

    - name: Extract Maven archive
      command: tar -zxvf /tmp/apache-maven.tar.gz -C /root

    - name: Rename extracted Maven directory to /root/maven
      command: mv /root/{{ maven_dir }} {{ maven_path }}

    - name: Set Maven path in .bashrc
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH={{ maven_path }}/bin:$PATH'
        state: present

    - name: Clone Maven project
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: HEAD

    - name: Create build.sh script with -DskipTests
      copy:
        dest: "{{ project_path }}/build.sh"
        mode: '0755'
        content: |
          #!/bin/bash
          echo "=== Running Maven Build ==="
          export PATH={{ maven_path }}/bin:$PATH
          cd {{ project_path }}
          mvn clean install -DskipTests

    - name: Run build.sh script
      shell: ./build.sh
      args:
        chdir: "{{ project_path }}"
